### ISSUE TITLE
Syntax Error: Unexpected Token while ./configure

### ISSUE THREAD

**Issue by raghuttamh** [nanograv/tempo#3]
When I run _./configure_ I get this error

> checking for gfortran... gfortran
> checking whether we are using the GNU Fortran 77 compiler... yes
> checking whether gfortran accepts -g... yes
> ./configure: line 4062: syntax error near unexpected token `FFLAGS+=" -ffixed-form -ffixed-line-length-none -std=legacy"'
> ./configure: line 4062: `    *gfortran* FFLAGS+=" -ffixed-form -ffixed-line-length-none -std=legacy"'

Please let me know what to do
Thanks!

**Comment by demorest** [comment]
Hi, can you give some more info like what is your OS, and what version of autotools and gfortran you have?

You could also try downloading the "release" version from this link.  This has the configure script pre-generated so may avoid whatever problem you are seeing: https://sourceforge.net/projects/tempo/files/tempo-13.103.tar.gz/download

**Comment by raghuttamh** [comment]
- OS: Ubuntu 20.04 LTS
- GNU automake 1.16.1
- GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

I could get things running with some help from [this Video](https://youtu.be/f5OJrU_gQJE)

**Comment by demorest** [comment]
OK great.  Any info on what caused the problem?

**Comment by raghuttamh** [comment]
I dont know the problem exactly.. paths were not as expected, I suppose..
